#set to appropriate working directory
#setwd("/Users/sarah/Dropbox/2020/COVID_parenting/COVID_script/")
covid_data_child <- read.csv("covid_data_child_scored.csv", header=TRUE, stringsAsFactors = FALSE)

library(reghelper)
library(ggplot2)

#Create centred variables for analysis
PARQhostile.mean <- mean(covid_data_child$PARQhostile, na.rm = TRUE)
totalSDQ.mean <- mean(covid_data_child$totalSDQ, na.rm = TRUE)
ch_age.mean <- mean(covid_data_child$ch_age, na.rm = TRUE)
totalFES.mean <- mean(covid_data_child$totalFES, na.rm = TRUE)
totalPTSD.mean <- mean(covid_data_child$totalPTSD, na.rm = TRUE)
SDQemo.mean <- mean(covid_data_child$SDQemo, na.rm = TRUE)
SDQhyp.mean <- mean(covid_data_child$SDQhyp, na.rm = TRUE)
SDQcon.mean <- mean(covid_data_child$SDQcon, na.rm = TRUE)
SDQpeer.mean <- mean(covid_data_child$SDQpeer, na.rm = TRUE)
Dep.mean <- mean(covid_data_child$Dep, na.rm = TRUE)
Anx.mean <- mean(covid_data_child$Anx, na.rm = TRUE)
Stress.mean <- mean(covid_data_child$Stress, na.rm = TRUE)
totalcov_dist.mean <- mean(covid_data_child$totalcov_dist, na.rm = TRUE)
covid_pos_num.mean <- mean(covid_data_child$covid_pos_num, na.rm = TRUE)
totalFES.mean <- mean(covid_data_child$totalFES, na.rm = TRUE)
covid_finance_num.mean <- mean(covid_data_child$covid_finance_num, na.rm = TRUE)
PARQcontrol.mean <- mean(covid_data_child$PARQcontrol, na.rm = TRUE)
PARQwarmth.mean <- mean(covid_data_child$PARQwarmth, na.rm = TRUE)
covid_data_child$PARQwarmth.c <- (covid_data_child$PARQwarmth-PARQwarmth.mean)
covid_data_child$PARQcontrol.c <- (covid_data_child$PARQcontrol-PARQcontrol.mean)
covid_data_child$covid_finance_num.c <- (covid_data_child$covid_finance_num-covid_finance_num.mean)
covid_data_child$totalFES.c <- (covid_data_child$totalFES-totalFES.mean)
covid_data_child$covid_pos_num.c <- (covid_data_child$covid_pos_num-covid_pos_num.mean)
covid_data_child$totalcov_dist.c <- (covid_data_child$totalcov_dist-totalcov_dist.mean)
covid_data_child$Stress.c <- (covid_data_child$Stress-Stress.mean)
covid_data_child$Anx.c <- (covid_data_child$Anx-Anx.mean)
covid_data_child$Dep.c <- (covid_data_child$Dep-Dep.mean)
covid_data_child$SDQpeer.c <- (covid_data_child$SDQpeer-SDQpeer.mean)
covid_data_child$SDQcon.c <- (covid_data_child$SDQcon-SDQcon.mean)
covid_data_child$SDQhyp.c <- (covid_data_child$SDQhyp-SDQhyp.mean)
covid_data_child$SDQemo.c <- (covid_data_child$SDQemo-SDQemo.mean)
covid_data_child$totalSDQ.c <- (covid_data_child$totalSDQ-totalSDQ.mean)
covid_data_child$PARQhostile.c <- (covid_data_child$PARQhostile-PARQhostile.mean)
covid_data_child$ch_age.c <- (covid_data_child$ch_age-ch_age.mean)
covid_data_child$totalFES.c <- (covid_data_child$totalFES-totalFES.mean)
covid_data_child$totalPTSD.c <- (covid_data_child$totalPTSD-totalPTSD.mean)

#check parent past disorder association with key variables
model <- lme(totalSDQ2 ~ par_past_mh_num , random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model <- lme(totalSDQ ~ par_past_mh_num , random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model <- lme(totalPARQ ~ par_past_mh_num , random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model <- lme(PARQhostile ~ par_past_mh_num , random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model <- lme(PARQwarmth ~ par_past_mh_num , random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model <- lme(totalcov_dist ~ par_past_mh_num , random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model <- lme(totalPTSD ~ par_past_mh_num , random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model <- lme(Dep ~ par_past_mh_num , random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model <- lme(Anx ~ par_past_mh_num , random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model <- lme(Stress ~ par_past_mh_num , random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
#parent past disorder is associated with SDQ, SDQ2, PTSD, DASS and covid distress, but not PARQ vbls
#consider adding as a covariate in models

#Series of mixed models below - a number of predictors & 6 outcome variables for each (SDQchange total, emo, con, hyp, peer subscales; PTSD)
#Models 1-3 test main effects (#1), 2-way child age/gender moderation (#2), and 3-way age/gender moderation (#3)
#Models 4-6 only for SDQchange outcomes and test the moderating effect of 'regular' SDQ scores
#Need to add in income as covariate

#PARQ hostile as predictor of total SDQ change since COVID
model1 <- lme(totalSDQ2 ~ PARQhostile.c+totalSDQ.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model1)
model2 <- lme(totalSDQ2 ~ PARQhostile.c*ch_age.c+PARQhostile.c*ch_gender_num+totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
anova(model1,model2)
model3 <- lme(totalSDQ2 ~ PARQhostile.c*ch_age.c*ch_gender_num+totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
anova(model2,model3)
model4 <- lme(totalSDQ2 ~ PARQhostile.c*totalSDQ.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
anova(model1,model4)
model5 <- lme(totalSDQ2 ~ PARQhostile.c*ch_age.c*totalSDQ.c+PARQhostile.c*ch_gender_num*totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
anova(model4,model5)
model6 <- lme(totalSDQ2 ~ PARQhostile.c*ch_age.c*ch_gender_num*totalSDQ.c+totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)
anova(model5,model6)

#FES as moderator - started to test this but wondering whether we want to.
model7 <- lme(totalSDQ2 ~ PARQhostile.c*totalFES.c+totalSDQ.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model7)

#model 4 best fitting - probe interaction
simple_slopes(model4)

graph_model(model4, y=totalSDQ2, x=PARQhostile.c, lines=totalSDQ.c)

#PARQ hostile as predictor of SDQ emo change since COVID
model <- lme(SDQemo2 ~ PARQhostile.c+SDQemo.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQemo2 ~ PARQhostile.c*ch_age.c+PARQhostile.c*ch_gender_num+SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQemo2 ~ PARQhostile.c*ch_age.c*ch_gender_num+SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQemo2 ~ PARQhostile.c*SDQemo.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQemo2 ~ PARQhostile.c*ch_age.c*SDQemo.c+PARQhostile.c*ch_gender_num*SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQemo2 ~ PARQhostile.c*ch_age.c*ch_gender_num*SDQemo.c+SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

model7 <- lme(SDQemo2 ~ PARQhostile.c*totalFES.c+SDQemo.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model7)

simple_slopes(model6)

graph_model(model6, y=SDQemo2, x=PARQhostile.c, lines=totalSDQ.c)

#PARQ hostile as predictor of SDQ hyp change since COVID
model <- lme(SDQhyp2 ~ PARQhostile.c+SDQhyp.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQhyp2 ~ PARQhostile.c*ch_age.c+PARQhostile.c*ch_gender_num+SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQhyp2 ~ PARQhostile.c*ch_age.c*ch_gender_num+SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQhyp2 ~ PARQhostile.c*SDQhyp.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQhyp2 ~ PARQhostile.c*ch_age.c*SDQhyp.c+PARQhostile.c*ch_gender_num*SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQhyp2 ~ PARQhostile.c*ch_age.c*ch_gender_num*SDQhyp.c+SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

model7 <- lme(SDQhyp2 ~ PARQhostile.c*totalFES.c*SDQhyp.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model7)

simple_slopes(model7)

graph_model(model7, y=SDQhyp2, x=PARQhostile.c, lines=totalFES.c)

data_lowSDQhyp <- subset(covid_data_child, covid_data_child$SDQhyp<=5)
data_highSDQhyp <- subset(covid_data_child, covid_data_child$SDQhyp>5)
model7a <- lme(SDQhyp2 ~ PARQhostile.c*totalFES.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = data_lowSDQhyp, na.action = na.exclude)
summary(model7a)
model7b <- lme(SDQhyp2 ~ PARQhostile.c*totalFES.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = data_highSDQhyp, na.action = na.exclude)
summary(model7b)

graph_model(model7b, y=SDQhyp2, x=PARQhostile.c, lines=totalFES.c)

#PARQ hostile as predictor of SDQ con change since COVID
model <- lme(SDQcon2 ~ PARQhostile.c+SDQcon.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQcon2 ~ PARQhostile.c*ch_age.c+PARQhostile.c*ch_gender_num+SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQcon2 ~ PARQhostile.c*ch_age.c*ch_gender_num+SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQcon2 ~ PARQhostile.c*SDQcon.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQcon2 ~ PARQhostile.c*ch_age.c*SDQcon.c+PARQhostile.c*ch_gender_num*SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQcon2 ~ PARQhostile.c*ch_age.c*ch_gender_num*SDQcon.c+SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

simple_slopes(model4)

graph_model(model4, y=SDQcon2, x=PARQhostile.c, lines=SDQcon.c)

#PARQ hostile as predictor of SDQ peer change since COVID
model <- lme(SDQpeer2 ~ PARQhostile.c+SDQpeer.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQpeer2 ~ PARQhostile.c*ch_age.c+PARQhostile.c*ch_gender_num+SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQpeer2 ~ PARQhostile.c*ch_age.c*ch_gender_num+SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQpeer2 ~ PARQhostile.c*SDQpeer.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQpeer2 ~ PARQhostile.c*ch_age.c*SDQpeer.c+PARQhostile.c*ch_gender_num*SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQpeer2 ~ PARQhostile.c*ch_age.c*ch_gender_num*SDQpeer.c+SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#PTSD as outcome
model1 <- lme(totalPTSD ~ PARQhostile.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model1)
model2 <- lme(totalPTSD ~ PARQhostile.c*ch_age.c+PARQhostile.c*ch_gender_num+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(totalPTSD ~ PARQhostile.c*ch_age.c*ch_gender_num+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)

#model 1 best fit - plot association
ggplot(covid_data_child, aes(x = PARQhostile.c, y = totalPTSD) ) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)

#DASS Dep as predictor of total SDQ change since COVID
model <- lme(totalSDQ2 ~ Dep.c+totalSDQ.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(totalSDQ2 ~ Dep.c*ch_age.c+Dep.c*ch_gender_num+totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(totalSDQ2 ~ Dep.c*ch_age.c*ch_gender_num+totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(totalSDQ2 ~ Dep.c*totalSDQ.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(totalSDQ2 ~ Dep.c*ch_age.c*totalSDQ.c+Dep.c*ch_gender_num*totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(totalSDQ2 ~ Dep.c*ch_age.c*ch_gender_num*totalSDQ.c+totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)


#DASS Dep as predictor of SDQ emo change since COVID
model <- lme(SDQemo2 ~ Dep.c+SDQemo.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQemo2 ~ Dep.c*ch_age.c+Dep.c*ch_gender_num+SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQemo2 ~ Dep.c*ch_age.c*ch_gender_num+SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQemo2 ~ Dep.c*SDQemo.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQemo2 ~ Dep.c*ch_age.c*SDQemo.c+Dep.c*ch_gender_num*SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQemo2 ~ Dep.c*ch_age.c*ch_gender_num*SDQemo.c+SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#DASS Dep as predictor of SDQ hyp change since COVID
model <- lme(SDQhyp2 ~ Dep.c+SDQhyp.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQhyp2 ~ Dep.c*ch_age.c+Dep.c*ch_gender_num+SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQhyp2 ~ Dep.c*ch_age.c*ch_gender_num+SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQhyp2 ~ Dep.c*SDQhyp.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQhyp2 ~ Dep.c*ch_age.c*SDQhyp.c+Dep.c*ch_gender_num*SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQhyp2 ~ Dep.c*ch_age.c*ch_gender_num*SDQhyp.c+SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#DASS Dep as predictor of SDQ con change since COVID
model <- lme(SDQcon2 ~ Dep.c+SDQcon.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQcon2 ~ Dep.c*ch_age.c+Dep.c*ch_gender_num+SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQcon2 ~ Dep.c*ch_age.c*ch_gender_num+SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQcon2 ~ Dep.c*SDQcon.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQcon2 ~ Dep.c*ch_age.c*SDQcon.c+Dep.c*ch_gender_num*SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQcon2 ~ Dep.c*ch_age.c*ch_gender_num*SDQcon.c+SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#DASS Dep as predictor of SDQ con change since COVID
model <- lme(SDQpeer2 ~ Dep.c+SDQpeer.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQpeer2 ~ Dep.c*ch_age.c+Dep.c*ch_gender_num+SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQpeer2 ~ Dep.c*ch_age.c*ch_gender_num+SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQpeer2 ~ Dep.c*SDQpeer.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQpeer2 ~ Dep.c*ch_age.c*SDQpeer.c+Dep.c*ch_gender_num*SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQpeer2 ~ Dep.c*ch_age.c*ch_gender_num*SDQpeer.c+SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#PTSD as outcome
model1 <- lme(totalPTSD ~ Dep.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model1)
model2 <- lme(totalPTSD ~ Dep.c*ch_age.c+PARQhostile.c*ch_gender_num+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(totalPTSD ~ Dep.c*ch_age.c*ch_gender_num+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)

ggplot(covid_data_child, aes(x = Dep.c, y = totalPTSD) ) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)

#DASS Anx as predictor of total SDQ change since COVID
model <- lme(totalSDQ2 ~ Anx.c+totalSDQ.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(totalSDQ2 ~ Anx.c*ch_age.c+Anx.c*ch_gender_num+totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(totalSDQ2 ~ Anx.c*ch_age.c*ch_gender_num+totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(totalSDQ2 ~ Anx.c*totalSDQ.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(totalSDQ2 ~ Anx.c*ch_age.c*totalSDQ.c+Anx.c*ch_gender_num*totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(totalSDQ2 ~ Anx.c*ch_age.c*ch_gender_num*totalSDQ.c+totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#DASS Anx as predictor of SDQ emo change since COVID
model <- lme(SDQemo2 ~ Anx.c+SDQemo.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQemo2 ~ Anx.c*ch_age.c+Anx.c*ch_gender_num+SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQemo2 ~ Anx.c*ch_age.c*ch_gender_num+SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQemo2 ~ Anx.c*SDQemo.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQemo2 ~ Anx.c*ch_age.c*SDQemo.c+Anx.c*ch_gender_num*SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQemo2 ~ Anx.c*ch_age.c*ch_gender_num*SDQemo.c+SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

simple_slopes(model4)

graph_model(model6, y=SDQemo2, x=Anx.c, lines=SDQemo.c)

#DASS Anx as predictor of SDQ hyp change since COVID
model <- lme(SDQhyp2 ~ Anx.c+SDQhyp.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQhyp2 ~ Anx.c*ch_age.c+Anx.c*ch_gender_num+SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQhyp2 ~ Anx.c*ch_age.c*ch_gender_num+SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQhyp2 ~ Anx.c*SDQhyp.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQhyp2 ~ Anx.c*ch_age.c*SDQhyp.c+Anx.c*ch_gender_num*SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQhyp2 ~ Anx.c*ch_age.c*ch_gender_num*SDQhyp.c+SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#DASS Anx as predictor of SDQ con change since COVID
model <- lme(SDQcon2 ~ Anx.c+SDQcon.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQcon2 ~ Anx.c*ch_age.c+Anx.c*ch_gender_num+SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQcon2 ~ Anx.c*ch_age.c*ch_gender_num+SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQcon2 ~ Anx.c*SDQcon.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQcon2 ~ Anx.c*ch_age.c*SDQcon.c+Anx.c*ch_gender_num*SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQcon2 ~ Anx.c*ch_age.c*ch_gender_num*SDQcon.c+SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#DASS Anx as predictor of SDQ peer change since COVID
model <- lme(SDQpeer2 ~ Anx.c+SDQpeer.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQpeer2 ~ Anx.c*ch_age.c+Anx.c*ch_gender_num+SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQpeer2 ~ Anx.c*ch_age.c*ch_gender_num+SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQpeer2 ~ Anx.c*SDQpeer.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQpeer2 ~ Anx.c*ch_age.c*SDQpeer.c+Anx.c*ch_gender_num*SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQpeer2 ~ Anx.c*ch_age.c*ch_gender_num*SDQpeer.c+SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#PTSD as outcome
model1 <- lme(totalPTSD ~ Anx.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model1)
model2 <- lme(totalPTSD ~ Anx.c*ch_age.c+PARQhostile.c*ch_gender_num+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(totalPTSD ~ Anx.c*ch_age.c*ch_gender_num+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)

ggplot(covid_data_child, aes(x = Anx.c, y = totalPTSD) ) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)

#DASS Stress as predictor of total SDQ change since COVID
model <- lme(totalSDQ2 ~ Stress.c+totalSDQ.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(totalSDQ2 ~ Stress.c*ch_age.c+Stress.c*ch_gender_num+totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(totalSDQ2 ~ Stress.c*ch_age.c*ch_gender_num+totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(totalSDQ2 ~ Stress.c*totalSDQ.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(totalSDQ2 ~ Stress.c*ch_age.c*totalSDQ.c+Stress.c*ch_gender_num*totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(totalSDQ2 ~ Stress.c*ch_age.c*ch_gender_num*totalSDQ.c+totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#DASS Stress as predictor of SDQ emo change since COVID
model <- lme(SDQemo2 ~ Stress.c+SDQemo.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQemo2 ~ Stress.c*ch_age.c+Stress.c*ch_gender_num+SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQemo2 ~ Stress.c*ch_age.c*ch_gender_num+SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQemo2 ~ Stress.c*SDQemo.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQemo2 ~ Stress.c*ch_age.c*SDQemo.c+Stress.c*ch_gender_num*SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQemo2 ~ Stress.c*ch_age.c*ch_gender_num*SDQemo.c+SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

simple_slopes(model4)

graph_model(model4, y=SDQemo2, x=Stress.c, lines=SDQemo.c)

#DASS Stress as predictor of SDQ hyp change since COVID
model <- lme(SDQhyp2 ~ Stress.c+SDQhyp.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQhyp2 ~ Stress.c*ch_age.c+Stress.c*ch_gender_num+SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQhyp2 ~ Stress.c*ch_age.c*ch_gender_num+SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQhyp2 ~ Stress.c*SDQhyp.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQhyp2 ~ Stress.c*ch_age.c*SDQhyp.c+Stress.c*ch_gender_num*SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQhyp2 ~ Stress.c*ch_age.c*ch_gender_num*SDQhyp.c+SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

simple_slopes(model4)

graph_model(model4, y=SDQhyp2, x=Stress.c, lines=SDQhyp.c)

#DASS Stress as predictor of SDQ con change since COVID
model <- lme(SDQcon2 ~ Stress.c+SDQcon.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQcon2 ~ Stress.c*ch_age.c+Stress.c*ch_gender_num+SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQcon2 ~ Stress.c*ch_age.c*ch_gender_num+SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQcon2 ~ Stress.c*SDQcon.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQcon2 ~ Stress.c*ch_age.c*SDQcon.c+Stress.c*ch_gender_num*SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQcon2 ~ Stress.c*ch_age.c*ch_gender_num*SDQcon.c+SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

simple_slopes(model4)

graph_model(model4, y=SDQcon2, x=Stress.c, lines=SDQcon.c)

#DASS Stress as predictor of SDQ peer change since COVID
model <- lme(SDQpeer2 ~ Stress.c+SDQpeer.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQpeer2 ~ Stress.c*ch_age.c+Stress.c*ch_gender_num+SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQpeer2 ~ Stress.c*ch_age.c*ch_gender_num+SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQpeer2 ~ Stress.c*SDQpeer.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQpeer2 ~ Stress.c*ch_age.c*SDQpeer.c+Stress.c*ch_gender_num*SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQpeer2 ~ Stress.c*ch_age.c*ch_gender_num*SDQpeer.c+SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#PTSD as outcome
model1 <- lme(totalPTSD ~ Stress.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model1)
model2 <- lme(totalPTSD ~ Stress.c*ch_age.c+PARQhostile.c*ch_gender_num+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(totalPTSD ~ Stress.c*ch_age.c*ch_gender_num+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)

ggplot(covid_data_child, aes(x = Stress.c, y = totalPTSD) ) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)

#totalcov_dist as predictor of total SDQ change since COVID
model <- lme(totalSDQ2 ~ totalcov_dist.c+totalSDQ.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(totalSDQ2 ~ totalcov_dist.c*ch_age.c+totalcov_dist.c*ch_gender_num+totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(totalSDQ2 ~ totalcov_dist.c*ch_age.c*ch_gender_num+totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(totalSDQ2 ~ totalcov_dist.c*totalSDQ.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(totalSDQ2 ~ totalcov_dist.c*ch_gender_num*totalSDQ.c+totalcov_dist.c*ch_age.c*totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(totalSDQ2 ~ totalcov_dist.c*ch_age.c*ch_gender_num*totalSDQ.c+totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

simple_slopes(model5)

model5a <- lme(totalSDQ2 ~ totalcov_dist.c*totalSDQ.c+ch_age.c+par_age+par_ed_ord, random=~1 | id, method="ML", data = data_female, na.action = na.exclude)
summary(model5a)
model5b <- lme(totalSDQ2 ~ totalcov_dist.c*totalSDQ.c+ch_age.c+par_age+par_ed_ord, random=~1 | id, method="ML", data = data_male, na.action = na.exclude)
summary(model5b)

graph_model(model5, y=totalSDQ2, x=totalcov_dist.c, lines=totalSDQ.c)

#totalcov_dist as predictor of SDQ emo change since COVID
model <- lme(SDQemo2 ~ totalcov_dist.c+SDQemo.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQemo2 ~ totalcov_dist.c*ch_age.c+totalcov_dist.c*ch_gender_num+SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQemo2 ~ totalcov_dist.c*ch_age.c*ch_gender_num+SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQemo2 ~ totalcov_dist.c*SDQemo.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQemo2 ~ totalcov_dist.c*ch_age.c*SDQemo.c+totalcov_dist.c*ch_gender_num*SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQemo2 ~ totalcov_dist.c*ch_age.c*ch_gender_num*SDQemo.c+SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

simple_slopes(model5)

model5a <- lme(SDQemo2 ~ totalcov_dist.c*SDQemo.c+ch_age.c+par_age+par_ed_ord, random=~1 | id, method="ML", data = data_female, na.action = na.exclude)
summary(model5a)
model5b <- lme(SDQemo2 ~ totalcov_dist.c*SDQemo.c+ch_age.c+par_age+par_ed_ord, random=~1 | id, method="ML", data = data_male, na.action = na.exclude)
summary(model5b)

graph_model(model5a, y=SDQemo2, x=totalcov_dist.c, lines=SDQemo.c)

#totalcov_dist as predictor of SDQ hyp change since COVID
model <- lme(SDQhyp2 ~ totalcov_dist.c+SDQhyp.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQhyp2 ~ totalcov_dist.c*ch_age.c+totalcov_dist.c*ch_gender_num+SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQhyp2 ~ totalcov_dist.c*ch_age.c*ch_gender_num+SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQhyp2 ~ totalcov_dist.c*SDQhyp.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQhyp2 ~ totalcov_dist.c*ch_age.c*SDQhyp.c+totalcov_dist.c*ch_gender_num*SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQhyp2 ~ totalcov_dist.c*ch_age.c*ch_gender_num*SDQhyp.c+SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#totalcov_dist as predictor of SDQ con change since COVID
model <- lme(SDQcon2 ~ totalcov_dist.c+SDQcon.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQcon2 ~ totalcov_dist.c*ch_age.c+totalcov_dist.c*ch_gender_num+SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQcon2 ~ totalcov_dist.c*ch_age.c*ch_gender_num+SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQcon2 ~ totalcov_dist.c*SDQcon.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQcon2 ~ totalcov_dist.c*ch_age.c*SDQcon.c+totalcov_dist.c*ch_gender_num*SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQcon2 ~ totalcov_dist.c*ch_age.c*ch_gender_num*SDQcon.c+SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

simple_slopes(model5)

data_female <- subset(covid_data_child, covid_data_child$ch_gender_num==1)
data_male <- subset(covid_data_child, covid_data_child$ch_gender_num==2)
model5a <- lme(SDQcon2 ~ totalcov_dist.c*SDQcon.c+ch_age.c+par_age+par_ed_ord, random=~1 | id, method="ML", data = data_female, na.action = na.exclude)
summary(model5a)
model5b <- lme(SDQcon2 ~ totalcov_dist.c*SDQcon.c+ch_age.c+par_age+par_ed_ord, random=~1 | id, method="ML", data = data_male, na.action = na.exclude)
summary(model5b)

#totalcov_dist as predictor of SDQ peer change since COVID
model <- lme(SDQpeer2 ~ totalcov_dist.c+SDQpeer.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQpeer2 ~ totalcov_dist.c*ch_age.c+totalcov_dist.c*ch_gender_num+SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQpeer2 ~ totalcov_dist.c*ch_age.c*ch_gender_num+SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQpeer2 ~ totalcov_dist.c*SDQpeer.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQpeer2 ~ totalcov_dist.c*ch_age.c*SDQpeer.c+totalcov_dist.c*ch_gender_num*SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQpeer2 ~ totalcov_dist.c*ch_age.c*ch_gender_num*SDQpeer.c+SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#PTSD as outcome
model1 <- lme(totalPTSD ~ totalcov_dist.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model1)
model2 <- lme(totalPTSD ~ totalcov_dist.c*ch_age.c+PARQhostile.c*ch_gender_num+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(totalPTSD ~ totalcov_dist.c*ch_age.c*ch_gender_num+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)

ggplot(covid_data_child, aes(x = totalcov_dist.c, y = totalPTSD) ) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)

#covid_pos_num as predictor of total SDQ change since COVID
model <- lme(totalSDQ2 ~ covid_pos_num.c+totalSDQ.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(totalSDQ2 ~ covid_pos_num.c*ch_age.c+covid_pos_num.c*ch_gender_num+totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(totalSDQ2 ~ covid_pos_num.c*ch_age.c*ch_gender_num+totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(totalSDQ2 ~ covid_pos_num.c*totalSDQ.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(totalSDQ2 ~ covid_pos_num.c*ch_gender_num*totalSDQ.c+covid_pos_num.c*ch_age.c*totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(totalSDQ2 ~ covid_pos_num.c*ch_age.c*ch_gender_num*totalSDQ.c+totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#covid_pos_num as predictor of SDQ emo change since COVID
model <- lme(SDQemo2 ~ covid_pos_num.c+SDQemo.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQemo2 ~ covid_pos_num.c*ch_age.c+covid_pos_num.c*ch_gender_num+SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQemo2 ~ covid_pos_num.c*ch_age.c*ch_gender_num+SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQemo2 ~ covid_pos_num.c*SDQemo.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQemo2 ~ covid_pos_num.c*ch_age.c*SDQemo.c+covid_pos_num.c*ch_gender_num*SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQemo2 ~ covid_pos_num.c*ch_age.c*ch_gender_num*SDQemo.c+SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#covid_pos_num as predictor of SDQ hyp change since COVID
model <- lme(SDQhyp2 ~ covid_pos_num.c+SDQhyp.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQhyp2 ~ covid_pos_num.c*ch_age.c+covid_pos_num.c*ch_gender_num+SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQhyp2 ~ covid_pos_num.c*ch_age.c*ch_gender_num+SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQhyp2 ~ covid_pos_num.c*SDQhyp.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQhyp2 ~ covid_pos_num.c*ch_age.c*SDQhyp.c+covid_pos_num.c*ch_gender_num*SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQhyp2 ~ covid_pos_num.c*ch_age.c*ch_gender_num*SDQhyp.c+SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#covid_pos_num as predictor of SDQ con change since COVID
model <- lme(SDQcon2 ~ covid_pos_num.c+SDQcon.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQcon2 ~ covid_pos_num.c*ch_age.c+covid_pos_num.c*ch_gender_num+SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQcon2 ~ covid_pos_num.c*ch_age.c*ch_gender_num+SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQcon2 ~ covid_pos_num.c*SDQcon.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQcon2 ~ covid_pos_num.c*ch_age.c*SDQcon.c+covid_pos_num.c*ch_gender_num*SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQcon2 ~ covid_pos_num.c*ch_age.c*ch_gender_num*SDQcon.c+SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#covid_pos_num as predictor of SDQ peer change since COVID
model <- lme(SDQpeer2 ~ covid_pos_num.c+SDQpeer.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQpeer2 ~ covid_pos_num.c*ch_age.c+covid_pos_num.c*ch_gender_num+SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQpeer2 ~ covid_pos_num.c*ch_age.c*ch_gender_num+SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQpeer2 ~ covid_pos_num.c*SDQpeer.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQpeer2 ~ covid_pos_num.c*ch_age.c*SDQpeer.c+covid_pos_num.c*ch_gender_num*SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQpeer2 ~ covid_pos_num.c*ch_age.c*ch_gender_num*SDQpeer.c+SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#PTSD as outcome
model1 <- lme(totalPTSD ~ covid_pos_num.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model1)
model2 <- lme(totalPTSD ~ covid_pos_num.c*ch_age.c+PARQhostile.c*ch_gender_num+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(totalPTSD ~ covid_pos_num.c*ch_age.c*ch_gender_num+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)

#covid_finance_num as predictor of total SDQ change since COVID
model <- lme(totalSDQ2 ~ covid_finance_num.c+totalSDQ.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(totalSDQ2 ~ covid_finance_num.c*ch_age.c+covid_finance_num.c*ch_gender_num+totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(totalSDQ2 ~ covid_finance_num.c*ch_age.c*ch_gender_num+totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(totalSDQ2 ~ covid_finance_num.c*totalSDQ.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(totalSDQ2 ~ covid_finance_num.c*ch_gender_num*totalSDQ.c+covid_finance_num.c*ch_age.c*totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(totalSDQ2 ~ covid_finance_num.c*ch_age.c*ch_gender_num*totalSDQ.c+totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#covid_finance_num as predictor of SDQ emo change since COVID
model <- lme(SDQemo2 ~ covid_finance_num.c+SDQemo.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQemo2 ~ covid_finance_num.c*ch_age.c+covid_finance_num.c*ch_gender_num+SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQemo2 ~ covid_finance_num.c*ch_age.c*ch_gender_num+SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQemo2 ~ covid_finance_num.c*SDQemo.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQemo2 ~ covid_finance_num.c*ch_age.c*SDQemo.c+covid_finance_num.c*ch_gender_num*SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQemo2 ~ covid_finance_num.c*ch_age.c*ch_gender_num*SDQemo.c+SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#covid_finance_num as predictor of SDQ hyp change since COVID
model <- lme(SDQhyp2 ~ covid_finance_num.c+SDQhyp.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQhyp2 ~ covid_finance_num.c*ch_age.c+covid_finance_num.c*ch_gender_num+SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQhyp2 ~ covid_finance_num.c*ch_age.c*ch_gender_num+SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQhyp2 ~ covid_finance_num.c*SDQhyp.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQhyp2 ~ covid_finance_num.c*ch_age.c*SDQhyp.c+covid_finance_num.c*ch_gender_num*SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQhyp2 ~ covid_finance_num.c*ch_age.c*ch_gender_num*SDQhyp.c+SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#covid_finance_num as predictor of SDQ con change since COVID
model <- lme(SDQcon2 ~ covid_finance_num.c+SDQcon.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQcon2 ~ covid_finance_num.c*ch_age.c+covid_finance_num.c*ch_gender_num+SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQcon2 ~ covid_finance_num.c*ch_age.c*ch_gender_num+SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQcon2 ~ covid_finance_num.c*SDQcon.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQcon2 ~ covid_finance_num.c*ch_age.c*SDQcon.c+covid_finance_num.c*ch_gender_num*SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQcon2 ~ covid_finance_num.c*ch_age.c*ch_gender_num*SDQcon.c+SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#covid_finance_num as predictor of SDQ peer change since COVID
model <- lme(SDQpeer2 ~ covid_finance_num.c+SDQpeer.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQpeer2 ~ covid_finance_num.c*ch_age.c+covid_finance_num.c*ch_gender_num+SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQpeer2 ~ covid_finance_num.c*ch_age.c*ch_gender_num+SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQpeer2 ~ covid_finance_num.c*SDQpeer.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQpeer2 ~ covid_finance_num.c*ch_age.c*SDQpeer.c+covid_finance_num.c*ch_gender_num*SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQpeer2 ~ covid_finance_num.c*ch_age.c*ch_gender_num*SDQpeer.c+SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#PTSD as outcome
model1 <- lme(totalPTSD ~ covid_finance_num.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model1)
model2 <- lme(totalPTSD ~ covid_finance_num.c*ch_age.c+PARQhostile.c*ch_gender_num+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(totalPTSD ~ covid_finance_num.c*ch_age.c*ch_gender_num+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)

#PARQcontrol as predictor of total SDQ change since COVID
model <- lme(totalSDQ2 ~ PARQcontrol.c+totalSDQ.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(totalSDQ2 ~ PARQcontrol.c*ch_age.c+PARQcontrol.c*ch_gender_num+totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(totalSDQ2 ~ PARQcontrol.c*ch_age.c*ch_gender_num+totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(totalSDQ2 ~ PARQcontrol.c*totalSDQ.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(totalSDQ2 ~ PARQcontrol.c*ch_gender_num*totalSDQ.c+PARQcontrol.c*ch_age.c*totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(totalSDQ2 ~ PARQcontrol.c*ch_age.c*ch_gender_num*totalSDQ.c+totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#PARQcontrol as predictor of SDQ emo change since COVID
model <- lme(SDQemo2 ~ PARQcontrol.c+SDQemo.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQemo2 ~ PARQcontrol.c*ch_age.c+PARQcontrol.c*ch_gender_num+SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQemo2 ~ PARQcontrol.c*ch_age.c*ch_gender_num+SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQemo2 ~ PARQcontrol.c*SDQemo.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQemo2 ~ PARQcontrol.c*ch_age.c*SDQemo.c+PARQcontrol.c*ch_gender_num*SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQemo2 ~ PARQcontrol.c*ch_age.c*ch_gender_num*SDQemo.c+SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#PARQcontrol as predictor of SDQ hyp change since COVID
model <- lme(SDQhyp2 ~ PARQcontrol.c+SDQhyp.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQhyp2 ~ PARQcontrol.c*ch_age.c+PARQcontrol.c*ch_gender_num+SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQhyp2 ~ PARQcontrol.c*ch_age.c*ch_gender_num+SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQhyp2 ~ PARQcontrol.c*SDQhyp.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQhyp2 ~ PARQcontrol.c*ch_age.c*SDQhyp.c+PARQcontrol.c*ch_gender_num*SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQhyp2 ~ PARQcontrol.c*ch_age.c*ch_gender_num*SDQhyp.c+SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

simple_slopes(model4)

#PARQcontrol as predictor of SDQ con change since COVID
model <- lme(SDQcon2 ~ PARQcontrol.c+SDQcon.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQcon2 ~ PARQcontrol.c*ch_age.c+PARQcontrol.c*ch_gender_num+SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQcon2 ~ PARQcontrol.c*ch_age.c*ch_gender_num+SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQcon2 ~ PARQcontrol.c*SDQcon.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQcon2 ~ PARQcontrol.c*ch_age.c*SDQcon.c+PARQcontrol.c*ch_gender_num*SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQcon2 ~ PARQcontrol.c*ch_age.c*ch_gender_num*SDQcon.c+SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)


#PARQcontrol as predictor of SDQ peer change since COVID
model <- lme(SDQpeer2 ~ PARQcontrol.c+SDQpeer.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQpeer2 ~ PARQcontrol.c*ch_age.c+PARQcontrol.c*ch_gender_num+SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQpeer2 ~ PARQcontrol.c*ch_age.c*ch_gender_num+SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQpeer2 ~ PARQcontrol.c*SDQpeer.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQpeer2 ~ PARQcontrol.c*ch_age.c*SDQpeer.c+PARQcontrol.c*ch_gender_num*SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQpeer2 ~ PARQcontrol.c*ch_age.c*ch_gender_num*SDQpeer.c+SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#PTSD as outcome
model1 <- lme(totalPTSD ~ PARQcontrol.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model1)
model2 <- lme(totalPTSD ~ PARQcontrol.c*ch_age.c+PARQhostile.c*ch_gender_num+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(totalPTSD ~ PARQcontrol.c*ch_age.c*ch_gender_num+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)

#PARQwarmth as predictor of total SDQ change since COVID
model <- lme(totalSDQ2 ~ PARQwarmth.c+totalSDQ.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(totalSDQ2 ~ PARQwarmth.c*ch_age.c+PARQwarmth.c*ch_gender_num+totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(totalSDQ2 ~ PARQwarmth.c*ch_age.c*ch_gender_num+totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(totalSDQ2 ~ PARQwarmth.c*totalSDQ.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(totalSDQ2 ~ PARQwarmth.c*ch_gender_num*totalSDQ.c+PARQwarmth.c*ch_age.c*totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(totalSDQ2 ~ PARQwarmth.c*ch_age.c*ch_gender_num*totalSDQ.c+totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#PARQwarmth as predictor of SDQ emo change since COVID
model <- lme(SDQemo2 ~ PARQwarmth.c+SDQemo.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQemo2 ~ PARQwarmth.c*ch_age.c+PARQwarmth.c*ch_gender_num+SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQemo2 ~ PARQwarmth.c*ch_age.c*ch_gender_num+SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQemo2 ~ PARQwarmth.c*SDQemo.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQemo2 ~ PARQwarmth.c*ch_age.c*SDQemo.c+PARQwarmth.c*ch_gender_num*SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQemo2 ~ PARQwarmth.c*ch_age.c*ch_gender_num*SDQemo.c+SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#PARQwarmth as predictor of SDQ hyp change since COVID
model <- lme(SDQhyp2 ~ PARQwarmth.c+SDQhyp.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQhyp2 ~ PARQwarmth.c*ch_age.c+PARQwarmth.c*ch_gender_num+SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQhyp2 ~ PARQwarmth.c*ch_age.c*ch_gender_num+SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQhyp2 ~ PARQwarmth.c*SDQhyp.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQhyp2 ~ PARQwarmth.c*ch_age.c*SDQhyp.c+PARQwarmth.c*ch_gender_num*SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQhyp2 ~ PARQwarmth.c*ch_age.c*ch_gender_num*SDQhyp.c+SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#PARQwarmth as predictor of SDQ con change since COVID
model <- lme(SDQcon2 ~ PARQwarmth.c+SDQcon.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQcon2 ~ PARQwarmth.c*ch_age.c+PARQwarmth.c*ch_gender_num+SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQcon2 ~ PARQwarmth.c*ch_age.c*ch_gender_num+SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQcon2 ~ PARQwarmth.c*SDQcon.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQcon2 ~ PARQwarmth.c*ch_age.c*SDQcon.c+PARQwarmth.c*ch_gender_num*SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQcon2 ~ PARQwarmth.c*ch_age.c*ch_gender_num*SDQcon.c+SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

simple_slopes(model4)

graph_model(model4, y=SDQcon2, x=PARQwarmth.c, lines=SDQcon.c)

#PARQwarmth as predictor of SDQ peer change since COVID
model <- lme(SDQpeer2 ~ PARQwarmth.c+SDQpeer.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQpeer2 ~ PARQwarmth.c*ch_age.c+PARQwarmth.c*ch_gender_num+SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQpeer2 ~ PARQwarmth.c*ch_age.c*ch_gender_num+SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQpeer2 ~ PARQwarmth.c*SDQpeer.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQpeer2 ~ PARQwarmth.c*ch_age.c*SDQpeer.c+PARQwarmth.c*ch_gender_num*SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQpeer2 ~ PARQwarmth.c*ch_age.c*ch_gender_num*SDQpeer.c+SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#PTSD as outcome
model1 <- lme(totalPTSD ~ PARQwarmth.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model1)
model2 <- lme(totalPTSD ~ PARQwarmth.c*ch_age.c+PARQhostile.c*ch_gender_num+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(totalPTSD ~ PARQwarmth.c*ch_age.c*ch_gender_num+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)

ggplot(covid_data_child, aes(x = PARQwarmth.c, y = totalPTSD) ) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)

#totalFES as predictor of total SDQ change since COVID
model <- lme(totalSDQ2 ~ totalFES.c+totalSDQ.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(totalSDQ2 ~ totalFES.c*ch_age.c+totalFES.c*ch_gender_num+totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(totalSDQ2 ~ totalFES.c*ch_age.c*ch_gender_num+totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(totalSDQ2 ~ totalFES.c*totalSDQ.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(totalSDQ2 ~ totalFES.c*ch_gender_num*totalSDQ.c+totalFES.c*ch_age.c*totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(totalSDQ2 ~ totalFES.c*ch_age.c*ch_gender_num*totalSDQ.c+totalSDQ.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#totalFES as predictor of SDQ emo change since COVID
model <- lme(SDQemo2 ~ totalFES.c+SDQemo.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQemo2 ~ totalFES.c*ch_age.c+totalFES.c*ch_gender_num+SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQemo2 ~ totalFES.c*ch_age.c*ch_gender_num+SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQemo2 ~ totalFES.c*SDQemo.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQemo2 ~ totalFES.c*ch_age.c*SDQemo.c+totalFES.c*ch_gender_num*SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQemo2 ~ totalFES.c*ch_age.c*ch_gender_num*SDQemo.c+SDQemo.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#totalFES as predictor of SDQ hyp change since COVID
model <- lme(SDQhyp2 ~ totalFES.c+SDQhyp.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQhyp2 ~ totalFES.c*ch_age.c+totalFES.c*ch_gender_num+SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQhyp2 ~ totalFES.c*ch_age.c*ch_gender_num+SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQhyp2 ~ totalFES.c*SDQhyp.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQhyp2 ~ totalFES.c*ch_age.c*SDQhyp.c+totalFES.c*ch_gender_num*SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQhyp2 ~ totalFES.c*ch_age.c*ch_gender_num*SDQhyp.c+SDQhyp.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#totalFES as predictor of SDQ con change since COVID
model <- lme(SDQcon2 ~ totalFES.c+SDQcon.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQcon2 ~ totalFES.c*ch_age.c+totalFES.c*ch_gender_num+SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQcon2 ~ totalFES.c*ch_age.c*ch_gender_num+SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQcon2 ~ totalFES.c*SDQcon.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQcon2 ~ totalFES.c*ch_age.c*SDQcon.c+totalFES.c*ch_gender_num*SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQcon2 ~ totalFES.c*ch_age.c*ch_gender_num*SDQcon.c+SDQcon.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#totalFES as predictor of SDQ peer change since COVID
model <- lme(SDQpeer2 ~ totalFES.c+SDQpeer.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model)
model2 <- lme(SDQpeer2 ~ totalFES.c*ch_age.c+totalFES.c*ch_gender_num+SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(SDQpeer2 ~ totalFES.c*ch_age.c*ch_gender_num+SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)
model4 <- lme(SDQpeer2 ~ totalFES.c*SDQpeer.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model4)
model5 <- lme(SDQpeer2 ~ totalFES.c*ch_age.c*SDQpeer.c+totalFES.c*ch_gender_num*SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model5)
model6 <- lme(SDQpeer2 ~ totalFES.c*ch_age.c*ch_gender_num*SDQpeer.c+SDQpeer.c+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model6)

#PTSD as outcome
model1 <- lme(totalPTSD ~ totalFES.c+par_age+ch_age.c+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model1)
model2 <- lme(totalPTSD ~ totalFES.c*ch_age.c+PARQhostile.c*ch_gender_num+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model2)
model3 <- lme(totalPTSD ~ totalFES.c*ch_age.c*ch_gender_num+par_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", data = covid_data_child, na.action = na.exclude)
summary(model3)

ggplot(covid_data_child, aes(x = totalFES.c, y = totalPTSD) ) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)

#Starting to play around with multiple imputation
#install.packages("mice")
library(mice)

midata <- mice(covid_data_child,m=20,maxit=50,meth='pmm',seed=500)

modelFit <- with(midata,lme(totalSDQ2 ~ PARQhostile.c*totalSDQ.c+par_age+ch_age+par_ed_ord+ch_gender_num, random=~1 | id, method="ML", na.action = na.exclude))
summary(pool(modelFit))
